### ISSUE TITLE
triangulate a very small domain

### ISSUE THREAD

**Issue by xiaolong7** [artem-ogre/CDT#115]
Hi, I would like to apply the CDT algorithm to triangulate a very small domain, like a long gap, please see the input file: 
[gap.txt](https://github.com/artem-ogre/CDT/files/10273358/gap.txt)

However, the algorithm failed to triangulate it. I am wondering if there is any constraint on the minimum edge length allowed in the triangulation process. Do you have any ideas on why the triangulation can not be performed? Any comments or suggestions are appreciated! Thank you for time and help!

**Comment by artem-ogre** [comment]
Thank you for opening the issue @xiaolong7 

Your input points have duplicates. Duplicates are not supported in CDT (see "Pre-conditions" in README.md).
Duplicates can be detected with `CDT::FindDuplicates` and fixed with `CDT::RemoveDuplicatesAndRemapEdges`.

Please let me know if I overlooked something and the issue needs to be re-opened.
