### ISSUE TITLE
Unexpected new vertices created; potential issues (or misuse of the API?)

### ISSUE THREAD

**Issue by jerstlouis** [artem-ogre/CDT#180]
Thank you for this great library.

I am evaluating whether this library serves our tesselation purposes and running into some issues.

It might be that I am misunderstanding how to use the API...

I am using the following code to tesselate a single polygon ([Canada1.geojson.zip](https://github.com/artem-ogre/CDT/files/15382439/Canada1.geojson.zip))
 with a single outer contour (no hole in this simple case, though support for holes is important). I don't believe the polygon has any self-intersection.

```C++
   CDT::Triangulation<double> cdt(
      CDT::VertexInsertionOrder::AsProvided,
      CDT::IntersectingConstraintEdges::NotAllowed, 1E-20);
   cdt.insertVertices(...);
   cdt.conformToEdges(...);
   cdt.eraseOuterTrianglesAndHoles();
   CDT::TriangleVec & triangles = cdt.triangles;
```
I should add that edge indices using any vertices with identical or < 1E-20 coordinates would already be mapped to the same vertex in the inserted vertices. There are cases in the polygon where the outer contour goes back on the same vertex, but it should be doing so following the validity rules (not intersecting itself).

There are two things confusing about the output:
- There are more output vertices than provided in the input with `cdt.insertVertices()` (indices past the number of vertices added, that do not correspond to any existing vertex), which are referenced in the resulting triangles.
- When matching those mismatched vertices to the closest original vertices, the result is what looks like inner contours and/or self-intersecting edges.

e.g., where this is expected (where blue lines represent the tesselation, and cyan lines represent outer contour edges identified from the tesselation result):

![expected](https://github.com/artem-ogre/CDT/assets/5140074/03715f3e-4e52-407f-9299-10f9135cfda9)

![resultExpectedFilled](https://github.com/artem-ogre/CDT/assets/5140074/40403fdc-63a3-44ff-9192-4ca93903f799)

the result is this:

![cdtResult](https://github.com/artem-ogre/CDT/assets/5140074/f253ae49-f5e8-4734-a970-be50abee12eb)

![resultFilled](https://github.com/artem-ogre/CDT/assets/5140074/6761e7e5-0b02-4149-b427-179bba6b50b8)

Whereabouts of zoomed in area in overall polygon:

![canada](https://github.com/artem-ogre/CDT/assets/5140074/008f1126-80a2-47b7-912f-28cc834742e4)

Notice the missing triangulated area and the narrow spaces outside the outer contours that became inner holes.
Some of this might be a result of matching the output vertices to the closest input ones, but I don't understand why the tesselation creates these unwanted new vertices in the first place?

Thank you for any insights you could provide about this!

**Comment by artem-ogre** [comment]
Hello, @jerstlouis,

Thank you for looking into CDT and taking all that time to describe the issues you are facing. I feel like most of these questions are answered in the documentation in one way or another.

- Additional points are created because `conformToEdges` is used. You should use `insertEdges` instead. Former produces conforming Delaunay triangulation and latter produces constraint triangulation (for example [here's](For each fixed edge that is not present in the triangulation its midpoint is recursively added until the original edge is represented by a sequence of its pieces. New vertices are inserted.) the explanation of differences). Please take the time to read documentation of the methods for more details: [`insertEdges`](https://artem-ogre.github.io/CDT/classCDT_1_1Triangulation.html#a1864bbe18731181ee5c0d91690d1e296), [`conformToEdges`](https://artem-ogre.github.io/CDT/classCDT_1_1Triangulation.html#aa3cdd6eb5ac29f84ce5e3ae123c926e1)
- Please read about [vertex insertion order](https://github.com/artem-ogre/CDT?tab=readme-ov-file#algorithm). You probably want to use `Auto` as it's generally faster.
- If you input is valid: no intersecting edges and no duplicate points, you don't need to set `minDistToConstraintEdge` at all, or can set it to zero.

Given all the points above the usage snippet should look something like this:
```cxx
CDT::Triangulation<double> cdt;
cdt.insertVertices(...);
cdt.insertEdges(...);
cdt.eraseOuterTrianglesAndHoles();
```
Please let me know if this answers your questions or if you have further questions.
I'm closing the issue for now.

**Comment by artem-ogre** [comment]
Thank you for the detailed feedback! ❤️ I will try to improve the documentation.

**Comment by artem-ogre** [comment]
I finally found some time to do the improvement you suggested: https://artem-ogre.github.io/CDT/classCDT_1_1Triangulation.html#a972f00c83b36c4a775aad30735f918d7
