### ISSUE TITLE
Get boundary edges

### ISSUE THREAD

**Issue by stla** [artem-ogre/CDT#76]
Hello,

  Is there a built-in way to get the boundary edges? Otherwise I can do it myself, by taking the edges of all the triangles and then the boundary edges are those which are unique. Maybe there's a better way?

**Comment by mdsumner** [comment]
there is rgl::boundary3d fwiw

**Comment by stla** [comment]
@mdsumner Thanks. I found `getBoundary3d` in **rgl**. Once you have a R `mesh3d`, there's also `Rvcg::vcgGetEdge`. It returns all the edges with an indicator of whether the edge is boundary.

**Comment by artem-ogre** [comment]
@stla What do you need the boundary edges for?

**Comment by stla** [comment]
@artem-ogre For plotting, I want to have the possibility to choose the color of the boundary edges. 

![face](https://user-images.githubusercontent.com/4466543/157542930-579efdf9-fd21-4d9e-96ee-86b201fedc45.png)

**Comment by mdsumner** [comment]
oh an sorry, I thought this was the @stla repo when I replied (not relevant here what R has )

**Comment by artem-ogre** [comment]
I see. There is no ready-to-use method for getting the boundary edges. So you will have to do it yourself.

 If you would like to do it in the most efficient way here are some ideas:
- Only check fixed edges, because only fixed edge can be a boundary edge
- You can do depth-peeling approach (for inspiration check `CalculateTriangleDepths` and `PeelLayer`) and record the boundary edges directly after each peeled layer

**Comment by stla** [comment]
Thanks. I finally use R to get them, with the **Rvcg** package, which has a function for doing that. This package is based on the C++ library **VCGLIB** and it is very fast.
