### ISSUE TITLE
how to call RemoveDuplicatesAndRemapEdges?

### ISSUE THREAD

**Issue by Meldryt** [artem-ogre/CDT#82]
how should we call RemoveDuplicatesAndRemapEdges() ?
second parameter accepts only type std::vector<Edge>& 
but there is no such member. We only have EdgeUSet fixedEdges.

**Comment by artem-ogre** [comment]
Hi, Meldryt,

`RemoveDuplicatesAndRemapEdges` is a helper utility for preprocessing input data _before_ it is passed to CDT. The reason is CDT does not support inputs with duplicates or crossing edges.

So you are not supposed to call it with `fixedEdges`, instead you are supposed to call it with vertices and edges that you intend to later pass to `insertVertices` and `insertEdges`.

**Comment by Meldryt** [comment]
Hi, @artem-ogre
Thx for quick answer. I guessed so.
I had to change my datatype before passing it. Is not as flexible as insertVertices, insertEdges

**Comment by artem-ogre** [comment]
Oh, I see. I could rewrite it with iterators-with-getters similar to `insertXXX` when there is time. 
Pull requests are very welcome too!
