### ISSUE TITLE
Question on a constrained Delaunay triangulation with intersecting edges

### ISSUE THREAD

**Issue by stla** [artem-ogre/CDT#95]
Hello,

  I inputted the four vertices of a square as vertices and the two diagonals of this square as constraint edges. Then the output I got is the triangulation with no triangle, no edge, and four fixed edges: the segments which join the center of the square to the vertices. Is it normal? I expected to get four triangles.

**Comment by artem-ogre** [comment]
It could be normal depending on how does the code look like. Can you show the code?

**Comment by stla** [comment]
My code is a bit special because I call it from Haskell. Here are the main points:

```cpp
  ......
  CDT::Triangulation<double> cdt(
    CDT::VertexInsertionOrder::AsProvided,
    CDT::IntersectingConstraintEdges::Resolve,
    0.0
  );
  ......
  cdt.insertVertices(vertices);
  cdt.insertEdges(Edges);
  cdt.eraseOuterTrianglesAndHoles();
  ......

```

**Comment by artem-ogre** [comment]
Oh, nice! Are there Haskell bindings? :)

Your output is normal:
- All triangles are removed with `eraseOuterTrianglesAndHoles` because they are not surrounded by constraints (e.g., you need to constrain square sides or use `eraseSuperTriangle`).
- Four edges are your 2 constraints split in 2 halves each. You can track to which input constraints pieces belong with `pieceToOriginals`

Hope it clears the things.

**Comment by stla** [comment]
Thanks, I didn't know `pieceToOriginals`, I will look at that.

I am the author of the Haskell bindings. I started two days ago: <https://github.com/stla/hcdt>. I have not mentioned your name and the license yet, I will do.
